### ISSUE TITLE
Error when listing array variables

### ISSUE THREAD

**Issue by pfirsich** [aphyt/aphytcomm#6]
When I try to print all variables, I get an uncaught exception:
```python
from aphyt import omron

def main():
    with omron.NSeries("172.29.20.53") as eip_conn:
        eip_conn.update_variable_dictionary()
        print(eip_conn.connected_cip_dispatcher.variables)

if __name__ == "__main__":
    main()
```

I get this exception:
```
Traceback (most recent call last):
  File "REDACTED/list_simple.py", line 11, in <module>
    main()
  File "REDACTED/list_simple.py", line 7, in main
    print(eip_conn.connected_cip_dispatcher.variables)
  File "REDACTED/aphytcomm/src/aphyt/cip/cip_datatypes.py", line 67, in __repr__
    return str(self.value())
               ^^^^^^^^^^^^
  File "REDACTED/aphytcomm/src/aphyt/cip/cip_datatypes.py", line 646, in value
    self.list_representation = self._recursive_data_to_array()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACTED/aphytcomm/src/aphyt/cip/cip_datatypes.py", line 616, in _recursive_data_to_array
    temp_array.append(temp_value.value())
                      ^^^^^^^^^^^^^^^^^^
  File "REDACTED/aphytcomm/src/aphyt/cip/cip_datatypes.py", line 494, in value
    member_value.value()
  File "REDACTED/aphytcomm/src/aphyt/cip/cip_datatypes.py", line 494, in value
    member_value.value()
  File "REDACTED/aphytcomm/src/aphyt/cip/cip_datatypes.py", line 246, in value
    return struct.unpack("<H", self.data)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 2 bytes
```

I looked into it a bit and the variables that yield an error (as seen from the stack trace) are CIPArray variables. For some reason the self.data member is b"" for them, so that the unpacking doesn't work.

It also happens with arrays in structs.

**Comment by pfirsich** [comment]
I think self.data is just only initialized by `read_variable`, so I will have to do this:
```python
    with omron.NSeries("172.29.20.53") as eip_conn:
        eip_conn.update_variable_dictionary()
        for k, v in eip_conn.connected_cip_dispatcher.variables.items():
            eip_conn.read_variable(k)
            print(v)
```

I think it's a bit confusing that currently `CIPDataType.value()` will either return wrong values (for e.g. integers) or throw/crash for arrays. I don't find a comment that states that the fields initialized by `update_variable_dictionary` (`connected_cip_dispatcher.variables`, `connected_cip_dispatcher.user_variables`, `connected_cip_dispatcher.system_variables`) can not be printed until `read_variable` has been called for them. 

Naively I would suggest it would be best if either .value() read the value on it's own (which seems like "hidden" IO, which is not great) or it would display an uninitialized value generally.

**Comment by aphyt** [comment]
I agree that the variable dictionaries are confusing when they're used directly. I mainly made and use them to make read_variable and write_variable methods in the higher level NSeries know how to pack and unpack data, but recognize that some people want to gather the variable names from the controller in their own program and this is the only way to do it currently. 

I'm on vacation this week, but I do plan on putting some thought on how to expose user and system variables more usefully in the actual NSeries class. They will have to be separate methods as reading the data type and structure of a variable and reading the contents of a variable are separate CIP messages and update_variable_dictionary is already a very expensive method in terms of network messages. Actually reading the contents of all variables should be something the programmer explicitly requests, otherwise I would be more than doubling the network traffic for folks that just wanted to know variable names and did not want to retrieve the contents at the same time.

**Comment by pfirsich** [comment]
Thank you for your response. What you said makes a lot of sense and like a good way forward.

What do you think about not making `print(var)` throw for variable objects that have not been read?

**Comment by aphyt** [comment]
I have added this enhancement and the changes are in version 0.1.22. All are accessible from the main NSeries object and an unread variable will not throw an exception (but they will not reflect the controller values until they are). The dictionary methods have a parameter that will allow the user to update the contents of the variables, but it is slow and should be used with that knowledge.

```
from aphyt import omron

eip_connection = omron.NSeries('192.168.250.9')
eip_connection.update_variable_dictionary()
print(eip_connection.variable_list())
print(eip_connection.system_variable_list())
print(eip_connection.user_variable_list())
# Variables with their default initialized state
print(eip_connection.user_variable_dictionary())
# Variables with their contents populated with controller values
print(eip_connection.user_variable_dictionary(update_contents=True))
```
