### ISSUE TITLE
List and read vars that are not 

### ISSUE THREAD

**Issue by juwalter** [aphyt/aphytcomm#7]
@aphyt 

Currently, it seems it is not possible to _list_ or _read_ (global) variables that are not configured _Publish only_ in section _Network publish_ in _Data->Global Variables_.

<img width="303" alt="image" src="https://github.com/user-attachments/assets/c85c3a14-b6c8-4b9a-943f-3f2ab935248c">

Is there a way to both _list_ and also _read_ variables that are e.g. _Do not publish_ or _Input_ or _Output_?

Many thanks in advance!

cc: @pfirsich

**Comment by aphyt** [comment]
Input and Output variables are both accessible via listing and reading as well. I was able to write to a variable assigned as an output as well. I would not recommend writing to an input as that should be overwritten by the cyclic data link.

Anything that is not Published or an Input or Output can not be listed or interacted with because without those characteristics enabled the variable will be ignored by the system services that process Ethernet/IP messages. 

```
from aphyt import omron

eip_connection = omron.NSeries('192.168.250.9')
eip_connection.update_variable_dictionary()
print(eip_connection.variable_list())
print(eip_connection.system_variable_list())
print(eip_connection.user_variable_list())
eip_connection.write_variable('Output_Var', True)
print(eip_connection.read_variable('Output_Var'))
```
